export const things = [
  "Active Volcanoes",
  "Beach Chair With Side Table",
  "Biceps & Triceps",
  "Big Blue Eyes",
  "Bits And Pieces",
  "Bold Measures",
  "Bonuses & Incentives",
  "Buzzwords",
  "Canvas Sneakers",
  "Car Cupholders",
  "Cars Trucks And Vans",
  "Castle Moat & Drawbridge",
  "Casual T-Shirts & Pants",
  "Champagne Bubbles",
  "Chubby Cheeks",
  "Clocks & Watches",
  "Coloring Book & Crayons",
  "Comic Books",
  "Complex Carbs",
  "Congested Freeways",
  "Daily & Weekly Calendar",
  "Day & Evening Classes",
  "Electric Cars",
  "Employee Benefits",
  "Fiction & Nonfiction",
  "Fingers And Toes",
  "Foot- Massaging Sandals",
  "Fuel Additives",
  "Funny Quotations",
  "Fur-Lined Winter Boots",
  "Giant Sand Dunes",
  "Golf Shoes",
  "Granite & Marble Floors",
  "Hamburger Wrappers",
  "Hammer And Nails",
  "Handbags & Shoes",
  "Hidden Talents",
  "High Hopes",
  "Homemade Gifts",
  "Honest Answers",
  "House Rules",
  "Job Postings",
  "Limericks",
  "Lipstick & Eye Shadow",
  "Lush Tropical Greenery",
  "Minor Adjustments",
  "Mixed Emotions",
  "Moisturizing Towelettes",
  "Morning Stretches",
  "Motorcycle Boots",
  "Motorcycles",
  "News Weather & Sports",
  "Outdoor Activities",
  "Parking Restrictions",
  "Party Favors",
  "Personal Movie Collection",
  "Plush Stuffed Animals",
  "Preemptive Measures",
  "Prom Dress & Tuxedo",
  "Public Sector",
  "Punctuation Marks",
  "Relaxing Spa Services",
  "Rose Petals",
  "Rustling Autumn Leaves",
  "Sample Questions",
  "Science And Technology",
  "Shearling- Lined Boots",
  "Shocks & Struts",
  "Spanish-Language Subtitles",
  "Stylish Sunglasses",
  "Subliminal Messages",
  "Tacks & Pushpins",
  "Tired And Aching Feet",
  "Traditional Christmas Gifts",
  "Unlimited Privileges",
  "Warm Caribbean Breezes",
  "Warmth & Compassion",
  "Waves Rolling Onto The Shore",
  "Wool Gloves"
];
